---
- name: Create cronjob
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
     apiVersion: batch/v1
     kind: CronJob
     metadata:
       name: "{{ job_sder.nom_cronjob }}"
       namespace: "{{ openjustice_sder_namespace }}"
     spec:
       schedule: "{{ job_sder.planification}}"
       successfulJobsHistoryLimit: 3
       failedJobsHistoryLimit: 3
       jobTemplate:
         spec:
           template:
             spec:
               containers:
                 - name: "{{ job_sder.nom_cronjob }}"
                   image: "{{ job_sder.nom_image }}"
                   imagePullPolicy: IfNotPresent
                   envFrom:
                     - configMapRef:
                         name: import-config
                     - secretRef:
                         name: import-secrets
               restartPolicy: OnFailure
       concurrencyPolicy: Forbid
...