---
- name: Deploy namespace
  import_tasks: namespace.yml

- name: Deploy configmap
  import_tasks: configmap.yml

- name: Deploy secrets
  import_tasks: secret.yml

- name: Deploy test scripts
  include_tasks: cronjob.yml
  loop: "{{ jobs_sder }}"
  loop_control:
    loop_var: job_sder