---
- name: create namespace
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_id }}"
        namespace: "{{ namespace }}"
...
