---
- name: Creation Namespace
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openjustice-sder
        namespace: "{{ openjustice_sder_namespace }}"
...
