---
- name: create secret
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app_id }}-secret"
        namespace: "{{ namespace }}"
      type: Opaque
      stringData:
        DB_USER: "{{ db_user }}"
        DB_PASS: "{{ db_pass }}"
        DB_USER_JURICA: "{{ db_user_jurica }}"
        DB_PASS_JURICA: "{{ db_pass_jurica }}"
        MONGO_URI: "{{ mongo_uri }}"
        INDEX_DB_URI: "{{ index_db_uri }}"
        GRCOM_DB_USER: "{{ grcom_db_user }}"
        GRCOM_DB_PASS: "{{ grcom_db_pass }}"
        PENAL_DB_USER: "{{ penal_db_user }}"
        PENAL_DB_PASS: "{{ penal_db_pass }}"
        PENAL_DB_HOST: "{{ penal_db_host }}"
        DB_HOST_JURICA: "{{ db_host_jurica }}"
        DB_HOST: "{{ db_host }}"
...
