image: docker:20.10.22
services:
  - docker:20.10.22-dind

stages:
  - build
  - deploy

build_import_job:
  stage: build
  variables:
    HTTP_PROXY: $HTTP_PROXY
    HTTPS_PROXY: $HTTPS_PROXY
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "$HTTP_PROXY"
    - echo "$HTTPS_PROXY"
    - docker build
        --build-arg http_proxy=$HTTP_PROXY
        --build-arg https_proxy=$HTTPS_PROXY
        -t $CI_REGISTRY/cour-de-cassation/openjustice-sder:import-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY/cour-de-cassation/openjustice-sder:import-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
  only:
    - master
    - migration_nouvelle_preprod
  tags:
    - docker


deploy_import_job:
  stage: deploy
  variables:
    DOLLAR: $DOLLAR
    KUBE_NAMESPACE: $KUBE_NAMESPACE
  script:
    - envsubst < .deploys/namespace.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
    - envsubst < .deploys/configmap.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
    - envsubst < .deploys/secret.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
    - envsubst < .deploys/import-cronjob.yaml | kubectl --kubeconfig=/home/gitlab-runner/.kube/$CI_COMMIT_BRANCH apply -f -
  only:
    - master
    - migration_nouvelle_preprod
  tags:
    - shell
  dependencies:
    - build_import_job