image: docker:20.10.22
services:
  - docker:20.10.22-dind

variables:
  dev: dev
  re7: preprod
  master: prod
  docker_image: '$CI_REGISTRY/cour-de-cassation/openjustice-sder:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA'

stages:
  - build
  - deploy

build_openjustice_sder:
  stage: build
  variables:
    HTTP_PROXY: $HTTP_PROXY_DEV
    HTTPS_PROXY: $HTTP_PROXY_DEV
    CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH
  script:
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - node_env=$(eval "echo \$$CI_COMMIT_BRANCH")
    - docker build
      --build-arg http_proxy=$HTTP_PROXY
      --build-arg https_proxy=$HTTPS_PROXY
      --build-arg ci_commit_branch=$CI_COMMIT_BRANCH
      --build-arg node_env=$node_env
      -t $docker_image .
    - docker push $docker_image
  only:
    - master
    - dev
    - re7
  tags:
    - docker

deploy_openjustice_sder:
  stage: deploy
  image: alpine/ansible:latest
  variables:
    DOLLAR: $$
  script:
    - inventaire=$(eval "echo \$$CI_COMMIT_BRANCH")
    - mkdir /root/.ssh
    - cat $SSH_KEY > /root/.ssh/id_rsa
    - cat $KNOWN_HOSTS > /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/known_hosts
    - |
      ansible-playbook \
            -e docker_image=$docker_image \
            -i ansible/inventory/$inventaire.yml \
            ansible/deploy_application.yml --vault-password-file=$ANSIBLE_VAULT_PASS
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "re7"
      when: manual
    - if: $CI_COMMIT_BRANCH == "dev"
      when: manual
  tags:
    - docker
  dependencies:
    - build_openjustice_sder
