version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: api-sder
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
      - './docker-compose/initdb.d/:/docker-entrypoint-initdb.d/'
  oracle-db:
    image: gvenzl/oracle-free
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=password
    volumes:
      - oracle-volume:/opt/oracle/oradata

  nodeapp:
    build: .
    container_name: import-sder
    depends_on:
      - mongodb
      - oracle-db
