CREATE USER GPCIV QUOTA unlimited ON USERS;

CREATE USER GPPEN QUOTA unlimited ON USERS;

CREATE USER GRCIV QUOTA unlimited ON USERS;

CREATE TABLE ANALYSE (
  ID_DOCUMENT     NUMBER         NULL,
  NUM_ANALYSE     NUMBER         NULL,
  PM              VARCHAR2(2000) NULL,
  AM1             VARCHAR2(2000) NULL,
  AM2             VARCHAR2(2000) NULL,
  AM3             VARCHAR2(2000) NULL,
  AM4             VARCHAR2(2000) NULL,
  AM5             VARCHAR2(2000) NULL,
  AM6             VARCHAR2(2000) NULL,
  AM7             VARCHAR2(2000) NULL,
  AM8             VARCHAR2(2000) NULL,
  AM9             VARCHAR2(2000) NULL,
  AM10            VARCHAR2(2000) NULL,
  AM11            VARCHAR2(2000) NULL,
  AM12            VARCHAR2(2000) NULL,
  SOMMAIRE        CLOB           NULL,
  TITRE_REFERENCE CLOB           NULL
);

CREATE TABLE DOCUMENT (
  ID_DOCUMENT                 NUMBER         NOT NULL,
  CLEF_ARRET                  NUMBER         NULL,
  TYPE_ARRET                  VARCHAR2(2000) NULL,
  NATURE_JURISPRUDENCE        VARCHAR2(2000) NULL,
  JURIDICTION                 VARCHAR2(2000) NULL,
  ID_CHAMBRE                  VARCHAR2(2000) NULL,
  COMPOSITION                 VARCHAR2(2000) NULL,
  NUM_DECISION                VARCHAR2(2000) NULL,
  DT_DECISION                 DATE           NULL,
  ID_SOLUTION                 VARCHAR2(2000) NULL,
  TEXTE_VISE                  VARCHAR2(2000) NULL,
  RAPROCHEMENT                VARCHAR2(2000) NULL,
  PRESIDENT                   VARCHAR2(2000) NULL,
  CONSRAP                     VARCHAR2(2000) NULL,
  AVOG                        VARCHAR2(2000) NULL,
  SOURCE                      VARCHAR2(2000) NULL,
  DOCTRINE                    VARCHAR2(2000) NULL,
  CAT_PUB                     VARCHAR2(2000) NULL,
  IND_CORRIGEJO               NUMBER         NULL,
  IND_VALIDEJO                NUMBER         NULL,
  TYPE_LIEN                   CHAR(1)        NULL,
  XML                         CLOB           NULL,
  DT_CREATION                 DATE           NULL,
  AUT_CREATION                VARCHAR2(2000) NULL,
  DT_MODIF                    DATE           NULL,
  AUT_MODIF                   VARCHAR2(2000) NULL,
  IND_BICC                    NUMBER         NULL,
  LIEN_BICC                   VARCHAR2(2000) NULL,
  IND_RCC                     NUMBER         NULL,
  LIEN_RCC                    VARCHAR2(2000) NULL,
  IND_WWW                     NUMBER         NULL,
  LIEN_WWW                    VARCHAR2(2000) NULL,
  SOURCEBIS                   VARCHAR2(2000) NULL,
  DT_ANO                      DATE           NULL,
  IND_ANO                     NUMBER(3,0)    DEFAULT 0 NULL,
  XMLA                        CLOB           NULL,
  AUT_ANO                     VARCHAR2(30)   NULL,
  DT_ENVOI_DILA               DATE           NULL,
  DT_MODIF_ANO                DATE           NULL,
  XMLT                        CLOB           NULL,
  XMLAT                       CLOB           NULL,
  IND_VERIF_ARRET             NUMBER(3,0)    DEFAULT 0 NULL,
  IND_VERIF_RAPPORT           NUMBER(3,0)    DEFAULT 0 NULL,
  IND_VERIF_AVIS              NUMBER(3,0)    DEFAULT 0 NULL,
  AUT_ANO_RAPPORT             VARCHAR2(30)   NULL,
  DT_ANO_RAPPORT              DATE           NULL,
  AUT_ANO_AVIS                VARCHAR2(30)   NULL,
  DT_ANO_AVIS                 DATE           NULL,
  COM_PRESSE                  CLOB           NULL,
  NOTE_EXPL                   CLOB           NULL,
  REF_ARRET_CEDH              VARCHAR2(2000) NULL,
  LIEN_ARRET_CEDH             VARCHAR2(2000) NULL,
  IND_PM                      INTEGER        NULL,
  IND_PHYM_GEOM               INTEGER        NULL,
  IND_ADRESSE                 INTEGER        NULL,
  IND_DT_NAISSANCE            INTEGER        NULL,
  IND_DT_DECE                 INTEGER        NULL,
  IND_DT_MARIAGE              INTEGER        NULL,
  IND_IMMATRICULATION         INTEGER        NULL,
  IND_CADASTRE                INTEGER        NULL,
  IND_CHAINE                  INTEGER        NULL,
  IND_COORDONNEE_ELECTRONIQUE INTEGER        NULL,
  IND_PRENOM_PROFESSIONEL     INTEGER        NULL,
  IND_NOM_PROFESSIONEL        INTEGER        NULL,
  OCCULTATION_SUPPLEMENTAIRE  VARCHAR2(2000) NULL,
  ID_FORMATION                VARCHAR2(3)    NULL,
  IND_BULLETIN                INTEGER        NULL,
  IND_RAPPORT                 INTEGER        NULL,
  IND_LETTRE                  INTEGER        NULL,
  IND_COMMUNIQUE              INTEGER        NULL
);

CREATE TABLE NUMPOURVOI (
  ID_DOCUMENT    NUMBER         NULL,
  LIB            VARCHAR2(2000) NULL,
  NUMPOURVOICODE VARCHAR2(7)    NULL
);

CREATE TABLE TITREREFERENCE (
  ID_DOCUMENT        NUMBER         NULL,
  NUM_ANALYSE        NUMBER         NULL,
  NUM_TITREREFERENCE NUMBER         NULL,
  PM                 VARCHAR2(2000) NULL,
  AM1                VARCHAR2(2000) NULL,
  AM2                VARCHAR2(2000) NULL,
  AM3                VARCHAR2(2000) NULL,
  AM4                VARCHAR2(2000) NULL,
  AM5                VARCHAR2(2000) NULL,
  AM6                VARCHAR2(2000) NULL,
  AM7                VARCHAR2(2000) NULL,
  AM8                VARCHAR2(2000) NULL,
  AM9                VARCHAR2(2000) NULL,
  AM10               VARCHAR2(2000) NULL,
  AM11               VARCHAR2(2000) NULL,
  AM12               VARCHAR2(2000) NULL
);

CREATE TABLE VIEW_PARTIE (
  ID_DOCUMENT       NUMBER         NOT NULL,
  TYPE_PERSONNE     VARCHAR2(100)  NULL,
  ID_PARTIE         NUMBER         NULL,
  NATURE_PARTIE     NUMBER         NULL,
  TYPE_PARTIE       VARCHAR2(100)  NULL,
  ID_TITRE          VARCHAR2(20)   NULL,
  NOM               VARCHAR2(100)  NULL,
  PRENOM            VARCHAR2(100)  NULL,
  NOM_MARITAL       VARCHAR2(100)  NULL,
  AUTRE_PRENOM      VARCHAR2(100)  NULL,
  ALIAS             VARCHAR2(100)  NULL,
  SIGLE             VARCHAR2(40)   NULL,
  DOMICILIATION     VARCHAR2(100)  NULL,
  LIG_ADR1          VARCHAR2(100)  NULL,
  LIG_ADR2          VARCHAR2(100)  NULL,
  LIG_ADR3          VARCHAR2(100)  NULL,
  CODE_POSTAL       VARCHAR2(20)   NULL,
  NOM_COMMUNE       VARCHAR2(100)  NULL,
  NUMERO            VARCHAR2(2000) NULL
);

CREATE TABLE GPCIV.AFF (
  ID_AFFAIRE              NUMBER          NOT NULL,
  ID_SERVICE              VARCHAR2(20)    NULL,
  ID_ELMSTR               NUMBER          NULL,
  ID_TYPAFF               VARCHAR2(20)    NULL,
  ID_NATAFF               VARCHAR2(20)    NULL,
  ID_MATIERE              VARCHAR2(20)    NULL,
  ID_SERVICE_DETENTEUR    VARCHAR2(20)    NULL,
  CODE                    NUMBER          NULL,
  CLE                     VARCHAR2(20)    NULL,
  DT_DECL                 DATE            NULL,
  DT_ENREG                DATE            NULL,
  IND_GREFFE              NUMBER          NULL,
  IND_DEP_CC              NUMBER          NULL,
  IND_MOTIVE              NUMBER          NULL,
  IND_FIN                 NUMBER          NULL,
  IND_AS                  NUMBER          NULL,
  IND_DESIST              NUMBER          NULL,
  IND_DECH                NUMBER          NULL,
  IND_DECH_EN_COURS       NUMBER          NULL,
  DT_DECH_EN_COURS        DATE            NULL,
  IND_AJ                  NUMBER          NULL,
  IND_RET_ROLE            NUMBER          NULL,
  IND_REQ                 NUMBER          NULL,
  IND_RET_EXPRO           NUMBER          NULL,
  IND_ART700              NUMBER          NULL,
  IND_ART1015             NUMBER          NULL,
  IND_ART628              NUMBER          NULL,
  IND_1009                NUMBER          NULL,
  IND_1009_1              NUMBER          NULL,
  IND_PI                  NUMBER          NULL,
  DT_DEM_DOS              DATE            NULL,
  DT_REC_DOS              DATE            NULL,
  DT_RET_DOS              DATE            NULL,
  DT_FIN_AFF              DATE            NULL,
  NB_PART_DEM             NUMBER          NULL,
  NB_PART_DEF             NUMBER          NULL,
  NB_PART_PI              NUMBER          NULL,
  NB_PART_PP              NUMBER          NULL,
  OBSERVATIONS            VARCHAR2(4000)  NULL,
  ID_AVOG                 VARCHAR2(20)    NULL,
  ID_CONSRAP              VARCHAR2(20)    NULL,
  ID_DECATT               NUMBER          NULL,
  ID_AUD                  NUMBER          NULL,
  ID_PREMDEM              NUMBER          NULL,
  ID_PREMDEF              NUMBER          NULL,
  DT_CREATION             DATE            NULL,
  DT_MODIF                DATE            NULL,
  AUT_CREATION            VARCHAR2(20)    NULL,
  AUT_MODIF               VARCHAR2(20)    NULL,
  ID_ARRET                NUMBER          NULL,
  NUM_LOT                 NUMBER          NULL,
  IND_DECH_INT            NUMBER          NULL,
  IND_DESIST_INT          NUMBER          NULL,
  IND_DESIST_PART         NUMBER          NULL,
  IND_DESIST_ACC          NUMBER          NULL,
  IND_DECH_INHIB          NUMBER          NULL,
  IND_AJ_EN_COURS         NUMBER          NULL,
  IND_CALCUL_DELAI        NUMBER          NULL,
  IND_PRESAISIE           NUMBER          NULL,
  IND_NVELLE_DECISION     NUMBER          NULL,
  NUM_DECL                NUMBER          NULL,
  IND_DESIST_GLOBAL       NUMBER          NULL,
  DT_RECEPISSE            DATE            NULL,
  DT_DESIGNCHAMBRE        DATE            NULL,
  ID_MOTIFDESIGNCHAMBRE   VARCHAR2(20)    NULL,
  IND_ART37               NUMBER          NULL,
  CLASSEMENT              VARCHAR2(4000)  NULL,
  IND_PROPOS_1009         NUMBER          NULL,
  DT_PROPOS_1009          DATE            NULL,
  AUT_PROPOS_1009         VARCHAR2(20)    NULL,
  IND_ABS_PROPOS_1009     NUMBER          NULL,
  IND_REJ_PROPOS_1009     NUMBER          NULL,
  ID_MOTIF_PROPOS_1009    NUMBER          NULL,
  OBSERVATIONS_AVO        VARCHAR2(4000)  NULL,
  IND_COMPLEXITE          NUMBER          NULL,
  ID_TYPE_NUM_LOT         NUMBER          NULL,
  ID_COMPO                NUMBER          NULL,
  ID_ORIENTATION_CHAMBRE  VARCHAR2(20)    NULL,
  IND_PREORIENTATION      NUMBER          NULL,
  JDEC_CODNAC             VARCHAR2(20)    NULL,
  JDEC_LIBNAC             VARCHAR2(4000)  NULL,
  JDEC_CODNACPART         VARCHAR2(20)    NULL,
  JDEC_LIBNACPART         VARCHAR2(1000)  NULL,
  ID_NAO                  VARCHAR2(20)    NULL,
  CASE_ID                 NUMBER          NULL
);

CREATE TABLE GPCIV.MATIERE (
  ID_MATIERE              VARCHAR2(20)    NULL,
  ID_SERVICE              VARCHAR2(20)    NULL,
  ID_NATAFF               VARCHAR2(20)    NULL,
  LIB                     VARCHAR2(4000)  NULL,
  IND_ETAT                NUMBER          NULL,
  SECTION                 VARCHAR2(4000)  NULL,
  ID_BLOC                 NUMBER          NULL
);

CREATE TABLE GPCIV.NAO (
  ID_NAO                 VARCHAR2(20)   NOT NULL,
  ID_SERVICE             VARCHAR2(20)   NULL,
  LIB                    VARCHAR2(4000) NULL,
  IND_ETAT               NUMBER         NULL,
  SECTION                VARCHAR2(4000) NULL,
  ID_BLOC                NUMBER         NULL
);

CREATE TABLE GPPEN.AFF (
  NO_AFFAIRE               NUMBER          NOT NULL,
  CODE                     NUMBER          NULL,
  CLE                      VARCHAR2(20)    NULL,
  ID_NATAFF                VARCHAR2(20)    NULL,
  TYPE_AFFAIRE             VARCHAR2(20)    NULL,
  DT_ENREG                 DATE            NULL,
  DT_DEPART                DATE            NULL,
  DT_DEM_DOS               DATE            NULL,
  DT_REC_DOS               DATE            NULL,
  DT_LIMITE_DEC            DATE            NULL,
  DT_EXP_DOSSIER           DATE            NULL,
  DT_DEM_COPIE_DECATT      DATE            NULL,
  ID_JURIDICT              NUMBER          NULL,
  ID_DECATT                NUMBER          NULL,
  FORMATION                VARCHAR2(20)    NULL,
  NUM_DECATT               VARCHAR2(20)    NULL,
  ID_TYPE_DECATT           NUMBER          NULL,
  ID_TYPE_ARRET            NUMBER          NULL,
  DT_DECATT                DATE            NULL,
  NB_DECATT                NUMBER          NULL,
  DT_ASPP                  DATE            NULL,
  DT_ASPG                  DATE            NULL,
  DT_ASGC                  DATE            NULL,
  NUM_ASPP                 NUMBER          NULL,
  NUM_ASPG                 NUMBER          NULL,
  NUM_ASGC                 NUMBER          NULL,
  OBS_ASPP                 VARCHAR2(4000)  NULL,
  OBS_ASPG                 VARCHAR2(4000)  NULL,
  OBS_ASGC                 VARCHAR2(4000)  NULL,
  REFEXTPP                 VARCHAR2(20)    NULL,
  REFEXTPG                 VARCHAR2(20)    NULL,
  REFEXTGC                 VARCHAR2(20)    NULL,
  DESCRIP_INFRACTION       VARCHAR2(4000)  NULL,
  OBSERVATIONS             VARCHAR2(4000)  NULL,
  ID_CONSRAP               VARCHAR2(20)    NULL,
  DT_NOMIN_AFF             DATE            NULL,
  DT_DEP_RAPPORT           DATE            NULL,
  DT_TRANS_AFF             DATE            NULL,
  NO_PERSONNEL             NUMBER          NULL,
  NB_CR                    NUMBER          NULL,
  ID_AG                    VARCHAR2(20)    NULL,
  DT_NOMIN_AG              DATE            NULL,
  NB_AG                    NUMBER          NULL,
  ID_AUDIENCE              NUMBER          NULL,
  TYPE_ROLE                NUMBER          NULL,
  DT_AUDIENCE              DATE            NULL,
  NB_AUD                   NUMBER          NULL,
  NB_RESIDUS               NUMBER          NULL,
  NB_DESISTEMENT           NUMBER          NULL,
  NB_RPRV                  NUMBER          NULL,
  NB_DEC                   NUMBER          NULL,
  NB_PREC                  NUMBER          NULL,
  NB_RAPP                  NUMBER          NULL,
  IND_AS                   NUMBER          NULL,
  IND_COURTE_PRESCRIP      NUMBER          NULL,
  IND_MOTIVE               NUMBER          NULL,
  IND_DELAIS               NUMBER          NULL,
  TYPE_DEC                 NUMBER          NULL,
  NB_PART_DEM              NUMBER          NULL,
  NB_AVOC_DEM              NUMBER          NULL,
  NB_PART_DEF              NUMBER          NULL,
  NB_AVOC_DEF              NUMBER          NULL,
  ID_SERVICE_DETENTEUR     VARCHAR2(20)    NULL,
  IND_ARRET_INCIDENT       NUMBER          NULL,
  IND_ARRET_CIVIL          NUMBER          NULL,
  DT_DEM_RETABLISS         DATE            NULL,
  IND_AJ                   NUMBER          NULL,
  IND_FIN                  NUMBER          NULL,
  DT_CREATION              DATE            NULL,
  DT_MODIF                 DATE            NULL,
  AUT_CREATION             VARCHAR2(20)    NULL,
  AUT_MODIF                VARCHAR2(20)    NULL,
  DT_ARRIVEE               DATE            NULL,
  MOTS_CLE                 VARCHAR2(4000)  NULL,
  DT_LIM_DEP_MEM           DATE            NULL,
  DT_DEP_MEM               DATE            NULL,
  OBS_MEM                  VARCHAR2(4000)  NULL,
  IND_R570                 NUMBER          NULL,
  ID_AFFAIRE               NUMBER          NULL,
  DT_RET_DOS               DATE            NULL,
  ID_ELMSTR                NUMBER          NULL,
  ID_PREMDEM               NUMBER          NULL,
  ID_PREMDEF               NUMBER          NULL,
  ID_AUD                   NUMBER          NULL,
  ID_AVOG                  NUMBER          NULL,
  IND_DESIST               NUMBER          NULL,
  IND_REQ                  NUMBER          NULL,
  ID_ARRET                 NUMBER          NULL,
  IND_AVANT_2000           NUMBER          NULL,
  NB_CD                    NUMBER          NULL,
  DT_EXP_ARRET             DATE            NULL,
  ID_COMPO                 NUMBER          NULL,
  IND_FIN_FORCEE           NUMBER          NULL,
  CASE_ID                  NUMBER          NULL,
  OBSERVATIONS_AVO         VARCHAR2(4000)  NULL
);

CREATE TABLE GRCIV.MATIERE (
  ID_MATIERE              VARCHAR2(20)    NULL,
  ID_SERVICE              VARCHAR2(20)    NULL,
  ID_NATAFF               VARCHAR2(20)    NULL,
  LIB                     VARCHAR2(4000)  NULL,
  IND_ETAT                NUMBER          NULL,
  SECTION                 VARCHAR2(4000)  NULL,
  ID_BLOC                 NUMBER          NULL
);
