apiVersion: v1
kind: ConfigMap
metadata:
  name: import-config
  namespace: ${KUBE_NAMESPACE}
data:
  DB_HOST: '10.14.78.202:1521/PROD'
  DB_TABLE: 'DOCUMENT'
  DB_ID_FIELD: 'ID_DOCUMENT'
  DB_ANO_TEXT_FIELD: 'XMLA'
  DB_STATE_FIELD: 'IND_ANO'
  DB_STATE_OK: '2'
  DB_VALID_FIELD: 'AUT_ANO'
  DB_TITRAGE_TABLE: 'TITREREFERENCE'
  DB_HOST_JURICA: '10.14.78.208:1521/jurica'
  DB_TABLE_JURICA: 'JCA_DECISION'
  DB_ID_FIELD_JURICA: 'JDEC_ID'
  DB_ANO_TEXT_FIELD_JURICA: 'HTMLA'
  DB_STATE_FIELD_JURICA: 'IND_ANO'
  DB_STATE_OK_JURICA: '2'
  DB_VALID_FIELD_JURICA: 'AUT_ANO'
  TITRAGE_FIELD: '_titrage'
  ENCODING: 'CP1252'
  MONGO_DBNAME: 'SDER'
  MONGO_JURINET_COLLECTION: 'rawJurinet'
  MONGO_JURICA_COLLECTION: 'rawJurica'
  MONGO_DILA_COLLECTION: 'rawDILA'
  MONGO_DECISIONS_COLLECTION: 'decisions'
  MONGO_ID: '_id'
  INDEX_DB_NAME: 'judilibre-index'
  PENAL_DB_HOST: '10.14.78.202:1521/PROD'
  API_PORT: '54345'
  API_ZONAGE_URI: 'http://172.16.118.98:8090'
  ZONING_URI: 'nlp-jurizonage-api.judilibre-prive.local'
  ZONING_PORT: '8090'
  ZONING_PROTOCOL: 'https'
  ZONING_NORMALIZE_SOURCE: 'true'
  META_URI: '172.16.118.98'
  META_PORT: '8081'
  META_PROTOCOL: 'http'
  JUDIFILTRE_URI: 'judifiltre.judilibre-prive.local'
  JUDIFILTRE_PROTOCOL: 'https'
