apiVersion: v1
kind: Secret
metadata:
  name: import-secrets
  namespace: ${KUBE_NAMESPACE}
type: Opaque
stringData:
  DB_USER: "${DB_USER}"
  DB_PASS: "${DB_PASS}"
  DB_USER_JURICA: "${DB_USER_JURICA}"
  DB_PASS_JURICA: "${DB_PASS_JURICA}"
  MONGO_URI: "${MONGO_URI}"
  INDEX_DB_URI: "${INDEX_DB_URI}"
  GRCOM_DB_USER: "${GRCOM_DB_USER}"
  GRCOM_DB_PASS: "${GRCOM_DB_PASS}"
  PENAL_DB_USER: "${PENAL_DB_USER}"
  PENAL_DB_PASS: "${PENAL_DB_PASS}"
