---
node_env: prod

db_user: "{{ vault_db_user }}"
db_pass: "{{ vault_db_pass }}"
db_user_jurica: "{{ vault_db_user_jurica }}"
db_pass_jurica: "{{ vault_db_pass_jurica }}"
mongo_uri: "{{ vault_mongo_uri }}"
index_db_uri: "{{ vault_index_db_uri }}"
grcom_db_user: "{{ vault_grcom_db_user }}"
grcom_db_pass: "{{ vault_grcom_db_pass }}"
penal_db_user: "{{ vault_penal_db_user }}"
penal_db_pass: "{{ vault_penal_db_pass }}"
db_host: "{{ vault_db_host }}"
db_host_jurica: "{{ vault_db_host_jurica }}"
penal_db_host: "{{ vault_penal_db_host }}"