---
node_env: dev
judifiltre_uri: "judifiltre.judilibre-prive.local"
meta_uri: "172.16.118.98"
zoning_uri: "nlp-jurizonage-api-service.nlp.svc.cluster.local:8090"
api_zonage_uri: "http://172.16.118.98:8090"