CREATE TABLE BLOCS_OCCULT_COMPL (
  ID_BLOC                     INTEGER NOT NULL,
  IND_PM                      INTEGER NOT NULL,
  IND_PHYM_GEOM               INTEGER NOT NULL,
  IND_ADRESSE                 INTEGER NOT NULL,
  IND_DT_NAISSANCE            INTEGER NOT NULL,
  IND_DT_DECE                 INTEGER NOT NULL,
  IND_DT_MARIAGE              INTEGER NOT NULL,
  IND_IMMATRICULATION         INTEGER NOT NULL,
  IND_CADASTRE                INTEGER NOT NULL,
  IND_CHAINE                  INTEGER NOT NULL,
  IND_COORDONNEE_ELECTRONIQUE INTEGER NOT NULL,
  IND_PRENOM_PROFESSIONEL     INTEGER NOT NULL,
  IND_NOM_PROFESSIONEL        INTEGER NOT NULL
);
