ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER ${DB_USER} IDENTIFIED BY ${DB_PASS};

GRANT ALL PRIVILEGES TO ${DB_USER};

CREATE USER ${DB_USER_JURICA} IDENTIFIED BY ${DB_PASS_JURICA};

GRANT ALL PRIVILEGES TO ${DB_USER_JURICA};

CREATE USER ${PENAL_DB_USER} IDENTIFIED BY ${PENAL_DB_PASS};

GRANT ALL PRIVILEGES TO ${PENAL_DB_USER};

CREATE USER ${GRCOM_DB_USER} IDENTIFIED BY ${GRCOM_DB_PASS};

GRANT ALL PRIVILEGES TO ${GRCOM_DB_USER};
